sudo: required
dist: trusty
language: cpp
compiler:
 - g++
#- clang++
cache:
 apt: true
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
#  - llvm-toolchain-precise-3.8
  packages:
   - g++-4.8
   - gcc-4.8
#  - g++-6
#  - gcc-6
#  - clang-3.8
#  - valgrind
before_install:
 - if [ "$CXX" = "g++" ];     then export CXX="g++-4.8"     CC="gcc-4.8";   fi
#- if [ "$CXX" = "g++" ];     then export CXX="g++-6"       CC="gcc-6";     fi
#- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
#install:
# - ./travis.sh
script:
 - dpkg-architecture; lscpu; env | sort
 - mkdir -p build && cd "$_" && cmake -DLIBCHAOS_ENABLE_TESTING=ON \
   -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} .. && make
 - ./bchaos; ./tchaos
